name: flutter_weather_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  geolocator: ^13.0.2
  bloc_pattern: ^3.0.1
  rxdart: ^0.28.0
  shimmer: ^3.0.0
  intl: ^0.19.0
  flutter_svg: ^2.0.17
  auto_size_text: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/

  